added the bash code and finished editing the JUnit tests

diff --git a/fms b/fms
--- a/fms
+++ b/fms
@@ -1,4 +1,52 @@
-fms compile
-fms run 3740
-fms compile-tests
-fms run-tests localhost 3740
+#fms compile
+#fms run 3740
+#fms compile-tests
+#fms run-tests localhost 3740
+
+#!/bin/bash
+
+SERVER_MODULE="familymapserver2"
+SHARED_MODULE="shared"
+
+#"com.example" is the package name.
+#"Server" would be the class with the main function.
+PACKAGE_NAME_TO_MAIN="src.server.ServerCommunicator"
+PACKAGE_NAME_TO_TEST_DRIVER="com.example.TestDriver"
+LIBS_FOLDER="libs"
+
+CODE_LOC="$SERVER_MODULE/src/main/* $SHARED_MODULE/*"
+TEST_CODE_LOC="$SERVER_MODULE/src/* $SHARED_MODULE/*"
+
+if [ "$1" == "compile" ]; then
+  CODE_DIR_AUTO="$(find $CODE_LOC -name '*.java')"
+  mkdir -p bin
+  javac -d "./bin" -classpath "./$LIBS_FOLDER/*" $CODE_DIR_AUTO
+  if [ $? -eq 0 ]; then
+    echo "SERVER COMPILATION SUCCESSFUL!"
+    exit
+  else
+    echo "SERVER COMPILATION FAILED!"
+  fi;
+elif [ "$1" == "run" ]; then
+  java -cp "./bin:./"$LIBS_FOLDER"/*" $PACKAGE_NAME_TO_MAIN $2
+elif [ "$1" == "compile-tests" ]; then
+  mkdir -p bin
+  CODE_DIR_AUTO="$(find $TEST_CODE_LOC -name '*.java')"
+  javac -d "./bin" -classpath "./$LIBS_FOLDER/*" $CODE_DIR_AUTO
+  if [ $? -eq 0 ]; then
+    echo "JUnit TEST COMPILATION SUCCESSFUL!"
+    exit
+  else
+    echo "JUnit TEST COMPILATION FAILED!"
+  fi;
+elif [ "$1" == "run-tests" ]; then
+  java -cp "./bin:./"$LIBS_FOLDER"/*" $PACKAGE_NAME_TO_TEST_DRIVER $2 $3
+elif [ "$1" == "clean" ]; then
+  echo "Removing ./bin folder"
+  rm -rf ./bin
+elif [ "$1" == "-help" ]; then
+  echo "USAGE: compile; run <port>; compile-tests; run-tests <host> <port>"
+else
+  echo "Invalid Command"
+  echo "USAGE: compile; run <port>; compile-tests; run-tests <host> <port>"
+fi;
